In [1]:
import pandas as pd

## Q1. Pandas version

In [2]:
pd.__version__

'1.2.4'

## Q2. Records count

In [4]:
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"

df = pd.read_csv(url)

df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [5]:
df.count

<bound method DataFrame.count of       model_year  origin fuel_type         drivetrain  num_doors  \
0           2006  Europe  Gasoline  Front-wheel drive          4   
1           2008  Europe    Diesel  Front-wheel drive          4   
2           1996    Asia  Gasoline  Front-wheel drive          5   
3           1989  Europe  Gasoline  Front-wheel drive          4   
4           1994     USA    Diesel  Front-wheel drive          3   
...          ...     ...       ...                ...        ...   
9995        2005     USA  Gasoline    All-wheel drive          4   
9996        1993    Asia  Gasoline    All-wheel drive          2   
9997        2014     USA  Gasoline    All-wheel drive          3   
9998        2004     USA    Hybrid   Rear-wheel drive          5   
9999        2011     USA    Diesel  Front-wheel drive          4   

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                    2180              6       243.0            3870   
1     

## Q3. Fuel types

In [8]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel', 'Hybrid'], dtype=object)

## Q4. Missing values

In [17]:
df.isnull().any()

model_year             False
origin                 False
fuel_type              False
drivetrain             False
num_doors              False
engine_displacement    False
num_cylinders          False
horsepower              True
vehicle_weight         False
acceleration            True
fuel_efficiency_mpg    False
dtype: bool

## Q5. Max fuel efficiency

In [11]:
df['fuel_efficiency_mpg'].max()

41.2

## Q6. Median value of horsepower

In [20]:
# Find the median value of the horsepower column in the dataset.
# Next, calculate the most frequent value of the same horsepower column.
# Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
# Now, calculate the median value of horsepower once again.

In [22]:
before_filling=df['horsepower'].median()
before_filling

254.0

In [23]:
most_frequent = df['horsepower'].mode()[0]
print(most_frequent)

252.0


In [24]:
df['horsepower'] = df['horsepower'].fillna(most_frequent)

In [25]:
after_filling=df['horsepower'].median()
after_filling

252.0

In [28]:
# Cross check if null values are removed
df['horsepower'].isnull().sum()

0

In [33]:
before_filling > after_filling 

True

## Q7. Sum of weights

In [36]:
# Select all the cars from Asia
# Select only columns vehicle_weight and model_year
# Select the first 7 values
# Get the underlying NumPy array. Let's call it X.
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
# Invert XTX.
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
# What's the sum of all the elements of the result?

In [147]:
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"

df = pd.read_csv(url)

df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [148]:
asia_cars=df[df['origin']=='Asia']
asia_cars

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1


In [160]:
selected_df = asia_cars[['vehicle_weight', 'model_year']]
selected_df 

,vehicle_weight,model_year
2,4240,1996
6,4310,1992
8,4230,1997
10,4420,1978
15,3950,2007
...,...,...
9984,4610,2011
9987,4530,2004
9990,3630,1975
9994,4610,1993


In [161]:
top_7 = selected_df.head(7)
top_7

,vehicle_weight,model_year
2,4240,1996
6,4310,1992
8,4230,1997
10,4420,1978
15,3950,2007
16,4750,2021
22,4450,2019


In [162]:
x = top_7.to_numpy()
x.shape

(7, 2)

In [163]:
x_transpose = x.T
x_transpose.shape

(2, 7)

In [164]:
xtx = x_transpose @ x
xtx

array([[131950500,  60750580],
       [ 60750580,  28041424]], dtype=int64)

In [165]:
import numpy as np

inverse_xtx = np.linalg.inv(xtx)
inverse_xtx

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [166]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y.shape

(7,)

In [170]:
w = inverse_xtx @ x_transpose @ y
w.shape

(2,)

In [171]:
w 

array([0.13644777, 0.2327492 ])

In [172]:
sum_result = np.sum(w)
sum_result

0.3691969690492638